### ISSUE TITLE
Signature file image does not show in Edit Account page

### ISSUE THREAD

**Issue by tanabana** [baljotsingh1986/employee-awards#8]
When I upload a new image for my user account with the Edit Account page, it saves it fine and I am able to make a new certificate with the new image I uploaded. However, the actual image link showing an image of the signature is broken. I get this message in the console:
<img width="561" alt="screen shot 2016-07-29 at 12 39 28 pm" src="https://cloud.githubusercontent.com/assets/8988551/17261363/325d6692-558a-11e6-9aa1-92edb7820a92.png">
However, after I run the following in the command line, I have the necessary permission to view the image file, and I can see it fine.
find ./ -type f -exec chmod 644 {} \;
I guess my question is if this is just an issue on my public_html, or if this is a problem on yours as well. Is there a way of automatically setting the read permissions of these image files that are put on the web server so that they are readable by the public when created?

**Comment by Harrings** [comment]
I have not had this issue when i am viewing the image so I am guessing it
is in your file permissions

**Comment by tanabana** [comment]
This is a problem specific to my server account, and not related to this application.
